FROM python:3.10-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV HF_HUB_TIMEOUT=120
ENV HF_HUB_DOWNLOAD_TIMEOUT=120

COPY backend/requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY backend backend

CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8080"]
